### ISSUE TITLE
Validity, compatibility, and integrity rule values are not displayed in the UI in read-only mode.

### ISSUE THREAD

**Issue by kovalmaksym** [Apicurio/apicurio-registry#4107]
### Feature or Problem Description

The UI in read-only mode does not display validity, compatibility, and integrity rule values. For instance, when a user selects values in the normal mode and then switches to read-only, the UI only presents the descriptions of the selected values without showing the actual values.

### Proposed Solution

Introduce a label field that exhibits the selected value for each rule in read-only mode.

### Additional Context

Normal mode:
<img width="1782" alt="image" src="https://github.com/Apicurio/apicurio-registry/assets/40665286/902f335b-0798-4a99-b0ee-96e3f29490d6">

Read-only:
<img width="1791" alt="image" src="https://github.com/Apicurio/apicurio-registry/assets/40665286/8b6df552-ef88-4e8d-8f52-a1bc5030a747">

**Comment by EricWittmann** [comment]
Fixed in https://github.com/EricWittmann/apicurio-registry/commit/17aba5ca844278d61f36980b7a2442e8e51ecb70

**Comment by Shawcs** [comment]
Hi @EricWittmann personally I still can't see any information about Validity, compatibility or integrity rule when I'm in read only. The image running in the 2.5.10.Final, it's the same display if the schema existed before the upgrade or was added after. In env variable (other than cert and connection) I'm using 
`
REGISTRY_UI_FEATURES_READONLY: true 
QUARKUS_PROFILE: prod 
REGISTRY_RULES_GLOBAL_VALIDITY: FULL 
ENABLE_CCOMPAT_CANONICAL_HASH_MODE:true
`

Am I missing something ?
