### ISSUE TITLE
Cannot deep link into the application - post-login redirects back to the Explore page

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#4948]

**Comment by olivier-hubaut** [comment]
We are facing this issue too, and seriously considering switching back to v2 as this make the product unusable for us.

**Comment by kevinrigotonem** [comment]
Issue is fixed in the latest version :)

**Comment by EricWittmann** [comment]
@olivier-hubaut any chance you can confirm this is true for you?

**Comment by olivier-hubaut** [comment]
@EricWittmann The issue seems to be partially fixed.
When you open a new browser instance and copy a deeplink in it, you are redirected to the apicurio home page, instead of an error page as it was before.
However, if you copy the link back into the same tab, you are then redirected to the correct content.
I think this might be related with how apicurio handle the redirect after the OIDC connection (we are using keycloak with kerberos for the identification of our users).

**Comment by EricWittmann** [comment]
OK thanks @olivier-hubaut - I think I'm seeing that same behavior.  I'll see what I can do.

**Comment by EricWittmann** [comment]
Fixed, I think, by:  

* https://github.com/Apicurio/apicurio-registry/pull/6183
