### ISSUE TITLE
Serdes jar does not include all dependencies

### ISSUE THREAD

**Issue by katheris** [Apicurio/apicurio-registry#702]
The serdes jar file does not include all the dependencies it requires. When running with a sample application that has only `org.apache.kafka:kafka-clients:2.5.0` and `io.apicurio:apicurio-registry-utils-serde:1.2.2.Final` in the dependencies section of the pom.xml I get the following error:

![image (20)](https://user-images.githubusercontent.com/11195226/88031936-2ef90b80-cb35-11ea-976a-af6b2146820d.png)

After some experimenting I make more progress by adding `javax.enterprise:cdi-api:1.2`, `org.jboss.resteasy:resteasy-core:4.5.5.Final` and `org.jboss.resteasy:resteasy-client:4.5.5.Final` but the jar file should already have all the dependencies I need, I shouldn't have to add others to my pom.xml manually.

**Comment by alesj** [comment]
I think this was all left out on purpose -- so you can use other REST clients, e.g. Jersey.

**Comment by gunnarmorling** [comment]
Hey, perhaps in that case you could at least provide some documentation of sorts which describes a complete set of dependencies known to work with that? Or, you could create another artifact, like _serde-with-deps_ which pulls in the right dependencies?

**Comment by alesj** [comment]
PR? ;-)

**Comment by gunnarmorling** [comment]
Well played ;)

>

**Comment by katheris** [comment]
@alesj So theoretically I can provide e.g. jax-rs instead? What about the CDI dependency? Is the expectation that I bring my own CDI implementation as well?

**Comment by alesj** [comment]
I thought CDI dependency is from RestEasy?
If not, then it is a bug.

I would guess that CDI is meant to be used server-side only anyway.
In that case you would already get server’ CDI impl.

**Comment by alesj** [comment]
Yeah, the idea is that the user/client provides its own rest impl; e.g.
Jersey

**Comment by EricWittmann** [comment]
Looking forward a bit, the next release will replace the client with one with fewer requirements.  So for now I would suggest we work around this as best we can while waiting for the new client impl.  It's pretty much already complete so we should be able to evaluate it soon.  

@carlesarnal

**Comment by EricWittmann** [comment]
@katheris Can you please check this against the latest from `master`.  The serdes classes should now be using the new REST client and this problem should be solved.

**Comment by rmarting** [comment]
This issue still exits in **1.2.3.Final** version of **apicurio-registry-utils-serde** dependency. To resolve it I have to add the dependencies described in the description of the issue.

**Comment by EricWittmann** [comment]
Yes it definitely still exists in *1.2.3.Final* - but could you check it with version *1.3.0.Final*?  It should be resolved there.

**Comment by rmarting** [comment]
Using the version **1.3.0.Final** I found other class not found (```org.glassfish.jersey.internal.RuntimeDelegateImpl```) when my code is consuming messages from a topic. The schema is already registered in my service-registry (by Apicurio web portal) so the issue is related when it is getting it from there.

Full stacktrace:

```
java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:315) ~[na:na]
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:93) ~[jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:210) ~[jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:111) ~[jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:96) ~[jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:172) ~[jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at io.apicurio.registry.client.RegistryRestClientImpl.parseResponseBody(RegistryRestClientImpl.java:325) ~[apicurio-registry-rest-client-1.3.0.Final.jar:na]
	at io.apicurio.registry.client.RegistryRestClientImpl.getArtifactByGlobalId(RegistryRestClientImpl.java:266) ~[apicurio-registry-rest-client-1.3.0.Final.jar:na]
	at io.apicurio.registry.client.CompatibleClient.getArtifactByGlobalId(CompatibleClient.java:170) ~[apicurio-registry-rest-client-1.3.0.Final.jar:na]
	at io.apicurio.registry.utils.serde.SchemaCache.lambda$getSchema$0(SchemaCache.java:41) ~[apicurio-registry-utils-serde-1.3.0.Final.jar:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
	at io.apicurio.registry.utils.serde.SchemaCache.getSchema(SchemaCache.java:40) ~[apicurio-registry-utils-serde-1.3.0.Final.jar:na]
	at io.apicurio.registry.utils.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:74) ~[apicurio-registry-utils-serde-1.3.0.Final.jar:na]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1310) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3500(Fetcher.java:128) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1541) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1377) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:677) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:632) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1315) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1248) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[kafka-clients-2.5.0.redhat-00003.jar:na]
	at com.jromanmartin.kafka.api.ConsumerController.pollFromTopic(ConsumerController.java:86) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

To fix it I added only the next dependency

```
<dependency>
	<groupId>org.jboss.resteasy</groupId>
	<artifactId>resteasy-client</artifactId>
	<version>4.5.6.Final</version>
</dependency>
```

My application is a simple KafkaProducer and KafkaConsumer running on a Spring Boot application.

**Comment by EricWittmann** [comment]
This is helpful, thanks @rmarting 

@carlesarnal The issue is here:  https://github.com/Apicurio/apicurio-registry/blob/master/rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientImpl.java#L325

This bit requires a JAX-RS implementation:  `MediaType.valueOf(...)`

Of course, that's just one symptom - looking at the new client interface we're still using a lot of JAX-RS classes such as `Response`.  What are your thoughts on eliminating JAX-RS references from the new interface?

We'll still have the issue of JAX-RS classes being used in the old client interface, and as a result we'll still need them in the serdes layer until we can release version 2.0.0 with breaking API changes.

**Comment by carlesarnal** [comment]
Hi @EricWittmann,

I'm in favour of removing all that JAX-RS classes. I'll have a look at this and improve this implementation.

**Comment by EricWittmann** [comment]
I believe this is complete.  We are no longer using jax-rs classes in the client implementation.  However, when using the "compatible" client (which is an implementation of the old client interface that delegates to the new client) we might still have issues.  Please re-open this if additional problems are found!

**Comment by rmarting** [comment]
@EricWittmann Which next release or snapshot includes it?

**Comment by katheris** [comment]
I tested this yesterday and managed to get it working with the below dependencies, so a much smaller set than before which was good. And to answer your qn @rmarting it's at least in 1.3.1-SNAPSHOT, it may have been included in an earlier one as well.
```        
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.apicurio</groupId>
            <artifactId>apicurio-registry-utils-serde</artifactId>
            <version>1.3.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>4.5.6.Final</version>
        </dependency>
```

**Comment by rmarting** [comment]
@katheris you are right, these are the minimum list of dependencies to work with the 1.3.1-SNAPSHOT version. 

When I see that this issue was closed I thought that **resteasy-client** dependency will not be longer needed, however I tested without it but the original issue appears with the following stacktrace:

```
java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[na:na]
```

So it seems that we need to add this "extra" dependeny to connect successfully with Apicurio registry. 

Maybe I am wrong, but the idea should be use only the **apicurio-registry-utils-serde** dependency, right?

**Comment by EricWittmann** [comment]
You're not wrong.  Ideally that should be the only dependency.  For now we'll have to document the issue (users might need the RE rest client dependency as well, depending on their application).  The old client interface that uses the JAX-RS classes has been deprecated - so the next major release should clean the last of this up.
